// Code generated by command: go run avo/asm.go -out dotint8_avx2_amd64.s -stubs dotint8_avx2_stub_amd64.go -pkg math. DO NOT EDIT.

//go:build amd64

package math

func dotInt8AVX2(q []float32, code []int8) float32
