//go:build amd64

package math

import "golang.org/x/sys/cpu"

// The explicit //go:build amd64 in the generated stub is re-added by `make
// asm`; avo does not emit one. Bare `go generate` drops it, which is harmless,
// since the _amd64.go filename is what actually constrains the file, but `make
// asm` keeps the two in agreement.
//go:generate go run avo/asm.go -out dotint8_avx2_amd64.s -stubs dotint8_avx2_stub_amd64.go -pkg math

// dotInt8AVX2 is generated by pkg/math/avo/asm.go (see dotint8_avx2_amd64.s).
// It assumes len(q) == len(code); DotInt8 enforces that before dispatch.

var (
	hasFastInt8 bool
	kernelName  string
	dotInt8Impl func(q []float32, code []int8) float32
)

func init() {
	hasFastInt8 = cpu.X86.HasAVX2 && cpu.X86.HasFMA && cpu.X86.HasAVX
	if hasFastInt8 {
		kernelName = "avx2"
		dotInt8Impl = dotInt8AVX2
		return
	}
	kernelName = "pure-go"
	dotInt8Impl = dotInt8Generic
}
