// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package mindb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type GetResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsGetResponse(buf []byte, offset flatbuffers.UOffsetT) *GetResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &GetResponse{}
	x.Init(buf, n+offset)
	return x
}

func FinishGetResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsGetResponse(buf []byte, offset flatbuffers.UOffsetT) *GetResponse {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &GetResponse{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedGetResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *GetResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *GetResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *GetResponse) Vectors(obj *Vector, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *GetResponse) VectorsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func GetResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func GetResponseAddVectors(builder *flatbuffers.Builder, vectors flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(vectors), 0)
}
func GetResponseStartVectorsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func GetResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
