// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package mindb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type StatsRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsStatsRequest(buf []byte, offset flatbuffers.UOffsetT) *StatsRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &StatsRequest{}
	x.Init(buf, n+offset)
	return x
}

func FinishStatsRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsStatsRequest(buf []byte, offset flatbuffers.UOffsetT) *StatsRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &StatsRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedStatsRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *StatsRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *StatsRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func StatsRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func StatsRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
