// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package mindb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type StatsResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsStatsResponse(buf []byte, offset flatbuffers.UOffsetT) *StatsResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &StatsResponse{}
	x.Init(buf, n+offset)
	return x
}

func FinishStatsResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsStatsResponse(buf []byte, offset flatbuffers.UOffsetT) *StatsResponse {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &StatsResponse{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedStatsResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *StatsResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *StatsResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *StatsResponse) VectorCount() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *StatsResponse) MutateVectorCount(n uint32) bool {
	return rcv._tab.MutateUint32Slot(4, n)
}

func (rcv *StatsResponse) Capacity() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *StatsResponse) MutateCapacity(n uint32) bool {
	return rcv._tab.MutateUint32Slot(6, n)
}

func (rcv *StatsResponse) Dims() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *StatsResponse) MutateDims(n uint32) bool {
	return rcv._tab.MutateUint32Slot(8, n)
}

func (rcv *StatsResponse) MemoryBytes() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *StatsResponse) MutateMemoryBytes(n uint64) bool {
	return rcv._tab.MutateUint64Slot(10, n)
}

func (rcv *StatsResponse) PayloadBytes() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *StatsResponse) MutatePayloadBytes(n uint64) bool {
	return rcv._tab.MutateUint64Slot(12, n)
}

func (rcv *StatsResponse) KernelName() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *StatsResponse) FastInt8() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *StatsResponse) MutateFastInt8(n bool) bool {
	return rcv._tab.MutateBoolSlot(16, n)
}

func (rcv *StatsResponse) Goarch() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *StatsResponse) WalEnabled() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *StatsResponse) MutateWalEnabled(n bool) bool {
	return rcv._tab.MutateBoolSlot(20, n)
}

func (rcv *StatsResponse) WalHealthy() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(22))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *StatsResponse) MutateWalHealthy(n bool) bool {
	return rcv._tab.MutateBoolSlot(22, n)
}

func StatsResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(10)
}
func StatsResponseAddVectorCount(builder *flatbuffers.Builder, vectorCount uint32) {
	builder.PrependUint32Slot(0, vectorCount, 0)
}
func StatsResponseAddCapacity(builder *flatbuffers.Builder, capacity uint32) {
	builder.PrependUint32Slot(1, capacity, 0)
}
func StatsResponseAddDims(builder *flatbuffers.Builder, dims uint32) {
	builder.PrependUint32Slot(2, dims, 0)
}
func StatsResponseAddMemoryBytes(builder *flatbuffers.Builder, memoryBytes uint64) {
	builder.PrependUint64Slot(3, memoryBytes, 0)
}
func StatsResponseAddPayloadBytes(builder *flatbuffers.Builder, payloadBytes uint64) {
	builder.PrependUint64Slot(4, payloadBytes, 0)
}
func StatsResponseAddKernelName(builder *flatbuffers.Builder, kernelName flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(5, flatbuffers.UOffsetT(kernelName), 0)
}
func StatsResponseAddFastInt8(builder *flatbuffers.Builder, fastInt8 bool) {
	builder.PrependBoolSlot(6, fastInt8, false)
}
func StatsResponseAddGoarch(builder *flatbuffers.Builder, goarch flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(7, flatbuffers.UOffsetT(goarch), 0)
}
func StatsResponseAddWalEnabled(builder *flatbuffers.Builder, walEnabled bool) {
	builder.PrependBoolSlot(8, walEnabled, false)
}
func StatsResponseAddWalHealthy(builder *flatbuffers.Builder, walHealthy bool) {
	builder.PrependBoolSlot(9, walHealthy, false)
}
func StatsResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
